### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by ghost** [GeordieP/clip-downloader#1]
====== RESTART: C:\Users\Anthony\Desktop\clip-downloader-master\tcd.py ======
downloads/lassiz/WonderfulRuffBlargNaut.mp4
Traceback (most recent call last):
  File "C:\Users\Anthony\Desktop\clip-downloader-master\tcd.py", line 29, in <module>
    mp4url = html.split('source\":\"')[1].split('\"}')[0]
IndexError: list index out of range
>>>

**Comment by GeordieP** [comment]
It looks like this script won't work anymore, sorry!

Seems like Twitch recently updated the clips page to be a JavaScript-only app; the page no longer works with JS disabled. The Python library that loads in the HTML doesn't execute JS, so the HTML it receives is essentially an empty page, and there's no .mp4 link for it to find.

You can still download clip videos yourself the old way, although it's unfortunate that we can't batch-download them anymore. If you load the clip page, and open the browser dev tools (usually f12 key, or right click > inspect), you'll see the HTML for the whole page. With that dev tools window selected, hit `CTRL (or CMD) + F` to open up the search box, type in `<video>`, and it should highlight the HTML line with the video in it. You'll see the link to the .mp4 there, and you can double click to select it for copy+paste.

Unfortunately I don't have the time to get the script working again. I'll mark it as broken on GitHub so people don't waste their time; Thank you for bringing this to my attention.
